services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URL : mongodb://mongo:27017/urlshortenerdb
      REDIS_URL : redis://redis:6379
      GOOGLE_SAFETY_API_KEY : AIzaSyAFyNRHB5cHgO4AwYEVI0LwydAwP7yfIpM
    depends_on:
      - mongo
      - redis
  mongo: 
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
